# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScrapeTool.ui'
#
# Created: Sun Feb 23 19:02:19 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from PySide.QtCore import QDate


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(380, 330)
        MainWindow.setMinimumSize(QtCore.QSize(380, 330))
        MainWindow.setMaximumSize(QtCore.QSize(380, 330))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Fiverr_EmailOrderScrape/Resources/python.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, -1, -1)
        self.formLayout.setSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.txtUsername = QtGui.QLineEdit(self.centralwidget)
        self.txtUsername.setEchoMode(QtGui.QLineEdit.Normal)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtUsername)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txtPassword = QtGui.QLineEdit(self.centralwidget)
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtPassword)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.txtFromDate = QtGui.QDateEdit(self.centralwidget)
        self.txtFromDate.setCalendarPopup(True)
        self.txtFromDate.setObjectName("txtFromDate")
        self.txtFromDate.setDate(QDate.currentDate())
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtFromDate)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.txtToDate = QtGui.QDateEdit(self.centralwidget)
        self.txtToDate.setCalendarPopup(True)
        self.txtToDate.setObjectName("txtToDate")
        self.txtToDate.setDate(QDate.currentDate())
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtToDate)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.txtLabel = QtGui.QLineEdit(self.centralwidget)
        self.txtLabel.setObjectName("txtLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtLabel)
        self.btnScrape = QtGui.QPushButton(self.centralwidget)
        self.btnScrape.setMinimumSize(QtCore.QSize(0, 40))
        self.btnScrape.setObjectName("btnScrape")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.btnScrape)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 2)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 3)
        self.lblProgress = QtGui.QLabel(self.centralwidget)
        self.lblProgress.setObjectName("lblProgress")
        self.gridLayout.addWidget(self.lblProgress, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Fiverr Revenue Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "User Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "From Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "To Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.btnScrape.setText(QtGui.QApplication.translate("MainWindow", "Scrape", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Email: <a mailto=\"me@saquibliaquat.com\"><span style=\" text-decoration: underline; color:#0000ff;\">me@saquibliaquat.com</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProgress.setText(QtGui.QApplication.translate("MainWindow", "Progress", None, QtGui.QApplication.UnicodeUTF8))

